export const categories = [
  { value: 0, label: "Any Category" },
  { value: 9, label: "General Knowledge" },
  { value: 10, label: "Books" },
  { value: 11, label: "Film" },
  { value: 12, label: "Music" },
  { value: 13, label: "Musicals & Theatres" },
  { value: 14, label: "Television" },
  { value: 15, label: "Video Games" },
  { value: 16, label: "Board Games" },
  { value: 17, label: "Nature" },
  { value: 18, label: "Computers" },
  { value: 19, label: "Mathematics" },
  { value: 20, label: "Mythology" },
  { value: 21, label: "Sports" },
  { value: 22, label: "Geography" },
  { value: 23, label: "History" },
  { value: 24, label: "Politics" },
  { value: 25, label: "Art" },
  { value: 26, label: "Celebrities" },
  { value: 27, label: "Animals" },
  { value: 28, label: "Vehicles" },
  { value: 29, label: "Comics" },
  { value: 30, label: "Gadgets" },
  { value: 31, label: "Anime & Manga" },
  { value: 32, label: "Cartoon & Animations" },
]
